"""add_is_deleted_and_seed_user

Revision ID: 051b9052245a
Revises: 0a602c6d1b02
Create Date: 2026-07-13 16:01:21.350196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051b9052245a'
down_revision: Union[str, Sequence[str], None] = '0a602c6d1b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'actor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.alter_column('notifications', 'actor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
