"""add_cascade_deletes

Revision ID: 0a602c6d1b02
Revises: 98b154423ffb
Create Date: 2026-07-11 10:20:58.434844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a602c6d1b02'
down_revision: Union[str, Sequence[str], None] = '98b154423ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('community_comment_likes_comment_id_fkey'), 'community_comment_likes', type_='foreignkey')
    op.create_foreign_key(None, 'community_comment_likes', 'community_comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('community_comment_shares_comment_id_fkey'), 'community_comment_shares', type_='foreignkey')
    op.create_foreign_key(None, 'community_comment_shares', 'community_comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('community_comments_post_id_fkey'), 'community_comments', type_='foreignkey')
    op.create_foreign_key(None, 'community_comments', 'community_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('community_post_likes_post_id_fkey'), 'community_post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'community_post_likes', 'community_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('community_post_saves_post_id_fkey'), 'community_post_saves', type_='foreignkey')
    op.create_foreign_key(None, 'community_post_saves', 'community_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('community_post_shares_post_id_fkey'), 'community_post_shares', type_='foreignkey')
    op.create_foreign_key(None, 'community_post_shares', 'community_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('community_reposts_original_post_id_fkey'), 'community_reposts', type_='foreignkey')
    op.create_foreign_key(None, 'community_reposts', 'community_posts', ['original_post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_comment_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_post_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'community_posts', ['post_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'community_comments', ['comment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_post_id_fkey'), 'notifications', 'community_posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('notifications_comment_id_fkey'), 'notifications', 'community_comments', ['comment_id'], ['id'])
    op.drop_constraint(None, 'community_reposts', type_='foreignkey')
    op.create_foreign_key(op.f('community_reposts_original_post_id_fkey'), 'community_reposts', 'community_posts', ['original_post_id'], ['id'])
    op.drop_constraint(None, 'community_post_shares', type_='foreignkey')
    op.create_foreign_key(op.f('community_post_shares_post_id_fkey'), 'community_post_shares', 'community_posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'community_post_saves', type_='foreignkey')
    op.create_foreign_key(op.f('community_post_saves_post_id_fkey'), 'community_post_saves', 'community_posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'community_post_likes', type_='foreignkey')
    op.create_foreign_key(op.f('community_post_likes_post_id_fkey'), 'community_post_likes', 'community_posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'community_comments', type_='foreignkey')
    op.create_foreign_key(op.f('community_comments_post_id_fkey'), 'community_comments', 'community_posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'community_comment_shares', type_='foreignkey')
    op.create_foreign_key(op.f('community_comment_shares_comment_id_fkey'), 'community_comment_shares', 'community_comments', ['comment_id'], ['id'])
    op.drop_constraint(None, 'community_comment_likes', type_='foreignkey')
    op.create_foreign_key(op.f('community_comment_likes_comment_id_fkey'), 'community_comment_likes', 'community_comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
