"""create portfolio table

Revision ID: 377425516319
Revises: aa981b595aca
Create Date: 2026-06-10 11:29:21.058634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '377425516319'
down_revision: Union[str, Sequence[str], None] = 'aa981b595aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_assets', sa.Column('custom_category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('portfolio_liabilities', sa.Column('custom_category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_liabilities', 'custom_category')
    op.drop_column('portfolio_assets', 'custom_category')
    # ### end Alembic commands ###
