"""create calendar events and exceptions tables

Revision ID: 7f772d0b37d7
Revises: b2a91f02d4e7
Create Date: 2026-05-31 21:09:26.759241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f772d0b37d7'
down_revision: Union[str, Sequence[str], None] = 'b2a91f02d4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
