"""add_market_watchlist

Revision ID: 9c97584033ad
Revises: 051b9052245a
Create Date: 2026-07-25 08:34:12.075056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c97584033ad'
down_revision: Union[str, Sequence[str], None] = '051b9052245a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_watchlists',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_watchlists')
    # ### end Alembic commands ###
